package com.quebecteh.modules.migrators.service;

import org.springframework.stereotype.Service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.quebecteh.commons.multitenancy.AbstractMultiTenancyCrudService;
import com.quebecteh.modules.migrators.domain.JSonSourceModel;
import com.quebecteh.modules.migrators.domain.SourceModel;

import ch.qos.logback.core.model.Model;
import lombok.SneakyThrows;

@Service
public class JSonSourceModelServiceImpl extends AbstractMultiTenancyCrudService<JSonSourceModel, Long> implements JSonSourceModelService  {

	
	
	@SneakyThrows
	public SourceModel createFromJson(String json) {
		
		ObjectMapper mapper = JsonMapper.builder().build();
		
		SourceModel model = mapper.readValue(json, JSonSourceModel.class);

		return model;
		
	}
	
	
	public static void main(String[] args) {
		
		
		String json = "{\r\n"
				+ "  \"name\": \"Contact\",\r\n"
				+ "  \"httpMethod\": \"POST\",\r\n"
				+ "  \"url\": \"https://www.zohoapis.com/inventory/v1/contacts?organization_id={{organization_id}}\",\r\n"
				+ "  \"headers\": {\r\n"
				+ "    \"Authorization\": \"Zoho-oauthtoken {{token}}\",\r\n"
				+ "    \"content-type\": \"application/json\"\r\n"
				+ "  },\r\n"
				+ "  \"fields\": [\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"contact_name\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": true,\r\n"
				+ "      \"description\": \"Name of the contact. This can be the name of an organisation or the name of an individual. Maximum length [200]\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"company_name\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Name of the contact's company. Maximum length [200]\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"payment_terms\",\r\n"
				+ "      \"type\": \"integer\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Net payment term for the customer.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"currency_id\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Currency ID of the customer's currency.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"website\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Website of the contact.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"contact_type\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Type of the contact. Allowed values are customer and vendor.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"custom_fields\",\r\n"
				+ "      \"type\": \"array\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Custom fields or Additional of the contact which we can create to add more information.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"billing_address\",\r\n"
				+ "      \"type\": \"object\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Billing address of the contact.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"shipping_address\",\r\n"
				+ "      \"type\": \"object\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Customer's shipping address to which the goods must be delivered.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"contact_persons\",\r\n"
				+ "      \"type\": \"array\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Person/Individual who represents a company.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"default_templates\",\r\n"
				+ "      \"type\": \"object\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Default templates for the contact.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"language_code\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Language of a contact. Allowed values: de, en, es, fr, it, ja, nl, pt, sv, zh.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"notes\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Comments about the payment made by the contact.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"vat_reg_no\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"VAT Registration number of a contact (🇬🇧 , Avalara Integration only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_reg_no\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"12 digit Tax Registration number of a contact (🇲🇽 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"country_code\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Two letter country code of a contact (🇬🇧 , Avalara Integration only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"vat_treatment\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"VAT treatment of the contact (🇬🇧 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_treatment\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"VAT treatment of the contact (🇲🇽 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_regime\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Tax Regime of the contact (🇲🇽 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"legal_name\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Legal Name of the contact (🇲🇽 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"is_tds_registered\",\r\n"
				+ "      \"type\": \"boolean\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Boolean to check if tax is registered (🇲🇽 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"avatax_exempt_no\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Exemption certificate number of the customer (Avalara Integration only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"avatax_use_code\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Used to group like customers for exemption purposes (Avalara Integration only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_exemption_id\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"ID of the tax exemption (🇺🇸 , 🇨🇦 , 🇦🇺 , 🇮🇳 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_authority_id\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"ID of the tax authority (🇺🇸 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_id\",\r\n"
				+ "      \"type\": \"boolean\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"ID of the tax or tax group that can be collected from the contact (🇺🇸 , 🇮🇳 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"is_taxable\",\r\n"
				+ "      \"type\": \"boolean\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Boolean to track the taxability of the customer (🇺🇸 , 🇨🇦 , 🇦🇺 , 🇮🇳 , 🇲🇽 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"facebook\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Facebook profile account of the contact. Maximum length [100].\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"twitter\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Twitter account of the contact. Maximum length [100].\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"place_of_contact\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Location of the contact (🇮🇳 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"gst_no\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"15 digit GST identification number of the customer/vendor (🇮🇳 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"gst_treatment\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"GST treatment of the contact. Allowed values are business_gst, business_none, overseas, consumer (🇮🇳 only).\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_authority_name\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Name of the Tax Authority.\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \"tax_exemption_code\",\r\n"
				+ "      \"type\": \"string\",\r\n"
				+ "      \"required\": false,\r\n"
				+ "      \"description\": \"Tax exemption code (🇺🇸 , 🇨🇦 , 🇦🇺 , 🇮🇳 only).\"\r\n"
				+ "    }\r\n"
				+ "  ]\r\n"
				+ "}";
		
		JSonSourceModelServiceImpl impl = new JSonSourceModelServiceImpl();
		SourceModel model = impl.createFromJson(json);
		System.out.println(model);
		
	}
	
}
